"""Code Worker role library (T049, FR-011).

Implements a :class:`TechnicalPlan` into a repo directory: one module +
unit-test module per implementation subtask, documentation when the
assessment requires it, and a local validation pass (compile check) so
broken code is caught before review. Deterministic and network-free.
"""

from __future__ import annotations

import py_compile
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field

from ai_factory.dev_workflow.technical_planner.planner import TechnicalPlan


class CodeWorkProduct(BaseModel):
    """What the code worker produced (files written + validation result)."""

    files: list[str] = Field(default_factory=list)
    validation: Literal["passed", "failed"] = "passed"
    errors: list[str] = Field(default_factory=list)
    doc_written: bool = False


_MODULE_SRC = '''"""Generated by the AI Factory code worker."""


def {func}() -> str:
    """Deterministic placeholder implementation."""
    return "ok"
'''

_TEST_SRC = '''"""Unit tests for {module}."""

from {module} import {func}


def test_{func}_returns_ok() -> None:
    assert {func}() == "ok"
'''


def _slug(text: str, n: int = 6) -> str:
    """Deterministic kebab-case slug used for artifact filenames."""
    import re

    words = re.findall(r"[a-z0-9]+", text.lower())[:n]
    return "-".join(words) if words else "decision"


def _safe_module(file: str) -> str:
    """Convert a file base name into an importable module identifier."""
    import re

    name = re.sub(r"[^A-Za-z0-9_]", "_", file[:-3])
    if name and name[0].isdigit():
        name = "_" + name
    return name or "module"


def _impl_subtasks(plan: TechnicalPlan) -> list:
    # Subtasks whose files include a non-test module (skip pure test/docs steps).
    return [
        t
        for t in plan.subtasks
        if any(
            f.endswith(".py") and not f.startswith("test_") and f != "test_suite.py"
            for f in t.files
        )
    ]


def implement(plan: TechnicalPlan, repo: Path) -> CodeWorkProduct:
    """Materialize ``plan`` into ``repo``; return the code-work product."""
    repo = Path(repo)
    repo.mkdir(parents=True, exist_ok=True)
    product = CodeWorkProduct()
    written: list[str] = []

    for idx, subtask in enumerate(_impl_subtasks(plan), start=1):
        for file in subtask.files:
            if not file.endswith(".py") or file == "test_suite.py":
                continue
            if file.startswith("test_"):
                continue
            func = f"impl_{idx}"
            module = _safe_module(file)
            target = repo / file
            target.parent.mkdir(parents=True, exist_ok=True)
            if file.startswith("static/"):
                target.write_text(_MODULE_SRC.format(func=func), encoding="utf-8")
            else:
                target.write_text(_MODULE_SRC.format(func=func), encoding="utf-8")
            # Write its unit test module next to it.
            test_target = repo / f"test_{module}.py"
            test_target.parent.mkdir(parents=True, exist_ok=True)
            test_target.write_text(
                _TEST_SRC.format(module=module, func=func), encoding="utf-8"
            )
            written.extend(
                [str(target.relative_to(repo)), str(test_target.relative_to(repo))]
            )

    # Documentation when assessment requires it (FR-011).
    if plan.assessment.documentation_required:
        readme = repo / "README.md"
        readme.write_text(
            f"# {plan.goal}\n\nGenerated documentation for {plan.spec_version_id}.\n",
            encoding="utf-8",
        )
        written.append("README.md")
        product.doc_written = True

    # Commit a linked ADR into the repo when an architectural decision exists
    # (FR-008) so the reviewer can verify adherence.
    if plan.adr is not None:
        adr_path = repo / "docs" / "adr" / f"{_slug(plan.adr.title)}.md"
        adr_path.parent.mkdir(parents=True, exist_ok=True)
        adr_path.write_text(
            f"# {plan.adr.title}\n\n## Decision\n{plan.adr.decision}\n\n"
            f"## Rationale\n{plan.adr.rationale}\n\n"
            "## Alternatives\n"
            f"{chr(10).join('- ' + a for a in plan.adr.alternatives)}\n",
            encoding="utf-8",
        )
        written.append(str(adr_path.relative_to(repo)))

    # Local validation: every written module compiles.
    errors: list[str] = []
    for rel in written:
        if not rel.endswith(".py"):
            continue
        try:
            py_compile.compile(str(repo / rel), doraise=True)
        except py_compile.PyCompileError as exc:
            errors.append(f"{rel}: {exc}")
    product.files = written
    product.validation = "failed" if errors else "passed"
    product.errors = errors
    return product


__all__ = ["CodeWorkProduct", "implement"]
